//
//  UIFont+Color.swift
//
//  Generated by Zeplin on 5/23/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIFont {
	class func MRTextStyleFont() -> UIFont? {
		return UIFont(name: "Helvetica-Bold", size: 80.0)
	}

	class func MRTextStyle5Font() -> UIFont? {
		return UIFont(name: "Helvetica", size: 50.0)
	}

	class func MRTextStyle3Font() -> UIFont {
		return UIFont.systemFontOfSize(24.0, weight: UIFontWeightBold)
	}

	class func MRTextStyle2Font() -> UIFont? {
		return UIFont(name: "PingFangTC-Medium", size: 20.0)
	}

	class func MRTextStyle10Font() -> UIFont {
		return UIFont.systemFontOfSize(20.0, weight: UIFontWeightMedium)
	}

	class func MRTextStyle6Font() -> UIFont? {
		return UIFont(name: "Helvetica", size: 20.0)
	}

	class func MRTextStyle4Font() -> UIFont {
		return UIFont.systemFontOfSize(10.0, weight: UIFontWeightRegular)
	}
}
